name: Testing CI

on:
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TSC
        run: pnpm run check

      - name: Prettier
        run: pnpm run check-format

      - name: ESLint
        run: pnpm run lint
